version: '3'

services:

  web:

    build: . 

    #command: python manage.py runserver 0.0.0.0:8000 jps

    volumes:
      - .:/app 

    ports: 
      - '8000:8000'

    entrypoint: /app/start.sh   